### ISSUE TITLE
Blender Kernel Crash

### ISSUE THREAD

**Issue by rawalkhirodkar** [panzi/blender_ipython#3]
Hi,

I am pretty new to this and would appreciate your help. It turns out that the python used by ipython on starting up uses the bundled python available with blender (this ofcourse could not import ipython resulting in crash). Any suggestions?

```
[I 17:03:16.720 NotebookApp] Kernel started: 3044b022-91a2-4fa0-a6cc-dfc431119a45
starting: blender -b -P /tmp/tmpmy_lfv4a_blender_ipython_kernel.py
Read prefs: /home/rawalkhirodkar/.config/blender/2.79/config/userpref.blend
found bundled python: /home/rawalkhirodkar/blender2.79/2.79/python
Traceback (most recent call last):
  File "/tmp/tmpmy_lfv4a_blender_ipython_kernel.py", line 4, in <module>
    from IPython.zmq.ipkernel import IPKernelApp
ImportError: No module named 'IPython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpmy_lfv4a_blender_ipython_kernel.py", line 6, in <module>
    from ipykernel.kernelapp import IPKernelApp
ImportError: No module named 'ipykernel'

Blender quit
```

**Comment by panzi** [comment]
Sorry, this thing is outdated and needs to be ported to recent IPython (Jupyter) versions.

**Comment by rawalkhirodkar** [comment]
I see. I would still try to fix it, any suggestions on plausible solutions?

**Comment by panzi** [comment]
Well, at first you have to install Jupyter. That is the core of this crash. But then nothing will work because a lot changed in the versions in between and one has to basically rewrite lots of this.

**Comment by komjum6** [comment]
I'd like to question the state of this. Is there a possibility user rawalkhirodkar fixed this? I've tried myself to fix it, but a certain OSError: [WinError 193] %1 is killing me... Or has user Panzi found a way to update this yet? I would love to see this revived.

**Comment by panzi** [comment]
At the moment I don't have time for this. Sorry. :(

**Comment by rawalkhirodkar** [comment]
@komjum6 I don't have a fix.
